# --- Database properties ---
spring:
    datasource:
        generate-unique-name: false
        name: tacocloud
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
    data:
        mongodb:
            host: localhost
            port: 27017
            database: tacoclouddb
    mongodb:
        embedded:
            version: 3.2.8