server:
    port: 8443
    ssl:
        key-store: src/main/resources/mykeys.jks
        key-store-password: password
        key-password: password
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/TacoCloud?currentSchema=taco_schema
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: false
        hibernate.ddl-auto: update
        properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    thymeleaf:
        cache: false
taco:
    orders:
        pageSize: 10