version: '3'

services:
    demo-message-broker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: demo-broker
        environment:
            - RABBITMQ_DEFAULT_USER = admin
            - RABBITMQ_DEFAULT_PASS = admin
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - messaging

networks:
    messaging:
        driver: bridge